# Generated by Django 3.0.5 on 2020-04-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spolen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoiceoption',
            old_name='answer',
            new_name='option',
        ),
    ]
